config/routes.rb
Rails.application.routes.draw do
  get 'documentals/index'
  post 'documentals/create'
  get 'documentals/new'
  get 'series/index'
  post 'series/create'
  get 'series/new'
  get 'movies/index'
  post 'movies/create'
  get 'movies/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documental.rb
class Documental < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentals_controller.rb
class DocumentalsController < ApplicationController
  def index
    @documentals = Documental.all
  end
  
  def create
    @documental = Documental.new(documental_params) #no sirve usar secuencia completa
    if @documental.save
      redirect_to '/documentals/index/', notice: 'Documental creado exitosamente.!'
    else
      redirect_to '/documentals/new/', notice: 'Intentalo nuevamente'
    end
  end

  def new
    @documental = Documental.new
  end

  private

  def documental_params
    params.require(:documental).permit(:name, :synopsis, :director)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  
  def create
    @movie = Movie.new(movie_params) #no sirve usar secuencia completa
    if @movie.save
      redirect_to '/movies/index/', notice: 'Película creada exitosamente.!'
    else
      redirect_to '/movies/new/', notice: 'Intentalo nuevamente'
    end
  end

  def new
    @movie = Movie.new
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  def index
    @series = Serie.all
  end
  
  def create
    @serie = Serie.new(serie_params) #no sirve usar secuencia completa
    if @serie.save
      redirect_to '/series/index/', notice: 'Serie creada exitosamente.!'
    else
      redirect_to '/series/new/', notice: 'Intentalo nuevamente'
    end
  end

  def new
    @serie = Serie.new
  end

  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentals_helper.rb
module DocumentalsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentals/create.html.erb
<h1>Documentals#create</h1>
<p>Find me in app/views/documentals/create.html.erb</p>

app/views/documentals/index.html.erb
<h5><%= "Dirección: #{documentals_index_path}" %></h5>


<h2>Listado de Documentales</h2>
<button type="button" class="btn btn-secondary"><%= link_to "Crear Documental", "/documentals/new", class: "nav-link" %></button>

<% @documentals.each do |documental| %>
  <div class="bg-body-secondary m-3 ">
    <h4><%= documental.name %></h4>
    <p><strong>Director:</strong> <%= documental.director %></p>
    <p><%= documental.synopsis %></p>
  </div>
  <hr>
<% end %>



<p>Find me in app/views/documentals/index.html.erb</p>

app/views/documentals/new.html.erb
<h1>Nuevo Documental</h1>

<%= form_with(model: @documental, url: '/documentals/create', local: true, class: "container")  do |form| %>
  <div class="form-group">
    <%= form.label :Titulo %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :Director %>
  <%= form.text_field :director, class: "form-control" %>
  </div>
    
  <div class="form-group">
    <%= form.label :Sinopsis %>
    <%= form.text_area :synopsis, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Crear Documental", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioMoviesDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!-- As a heading -->
  <nav class="navbar bg-body-tertiary bg-dark" bg-dark data-bs-theme="dark">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">
      <%= link_to "Root Pelis", root_path, class: "custom-link" %>
      </span>
      <span class="navbar-brand mb-0 h1">
      <%= link_to "Series", "/series/index", class: "custom-link" %>
      </span>
      <span class="navbar-brand mb-0 h1">
      <%= link_to "Documentales", "/documentals/index", class: "custom-link" %>
      </span>
    </div>
  </nav>


  <% if notice %>
    <div class="notice link-success">
    <%= notice %>
  </div>
  <% end %>

  <body>
    <div class=container>
      <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h5><%= "Dirección: #{root_path}" %></h5>


<h2>Listado de Pelis</h2>
<button type="button" class="btn btn-secondary"><%= link_to "Crear Movie", "/movies/new", class: "nav-link" %></button>

<% @movies.each do |movie| %>
  <div class="bg-body-secondary m-3 ">
    <h4>Nombre:<%= movie.name %></h4>
    <p><strong>Director:</strong> <%= movie.director %></p>
    <p>sinopsis: <%= movie.synopsis %></p>
  </div>
  <hr>
<% end %>



<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/new.html.erb
<h1>Nueva Película</h1>

<%= form_with(model: @movie, url: '/movies/create', local: true, class: "container")  do |form| %>
  <div class="form-group">
    <%= form.label :Titulo %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :Director %>
  <%= form.text_field :director, class: "form-control" %>
  </div>
    
  <div class="form-group">
    <%= form.label :Sinopsis %>
    <%= form.text_area :synopsis, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Crear Película", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h5><%= "Dirección: #{series_index_path}" %></h5>


<h2>Listado de Series</h2>
<button type="button" class="btn btn-secondary"><%= link_to "Crear Serie", "/series/new", class: "nav-link" %></button>

<% @series.each do |serie| %>
  <div class="bg-body-secondary m-3 ">
    <h4><%= serie.name %></h4>
    <p><strong>Director:</strong> <%= serie.director %></p>
    <p><%= serie.synopsis %></p>
  </div>
  <hr>
<% end %>



<p>Find me in app/views/series/index.html.erb</p>

app/views/series/new.html.erb
<h1>Nueva Serie</h1>

<%= form_with(model: @serie, url: '/series/create', local: true, class: "container")  do |form| %>
  <div class="form-group">
    <%= form.label :Titulo %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :Director %>
  <%= form.text_field :director, class: "form-control" %>
  </div>
    
  <div class="form-group">
    <%= form.label :Sinopsis %>
    <%= form.text_area :synopsis, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Crear Serie", class: "btn btn-secondary" %>
  </div>
<% end %>